spring:
  application:
    name: blackjack-webflux

  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack

  r2dbc:
    url: r2dbc:mysql://localhost:3306/blackjack
    username: root
    password: root

  sql:
    init:
      mode: always

server:
  port: 8080
